version: "3.8"

services:
  flask_app:
    build: ./flask_app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: python server.py

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage:
